---
title: "day 10"
author: "Guillermo Romero"
date: "2022-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)
library(sf)
library(ggthemes)
```

```{r}
lizards <- read_csv(here::here("data_tidy","lizards.csv"))

```

```{r}
# lizards_count <- lizards |> 
#   mutate(date = lubridate::mdy(date)) |> 
#   count(year = lubridate::year(date, common_name) |> 
#   drop_na()
# 
# lizards_count
```
```{r}
# ggplot(data = lizard_counts, aes(x = year, y = common_name)) |> 
#   geom_tile()
```
# Beeswarm plot

```{r}
whiptails <- lizards |> 
  filter(common_name == "western whiptail") 
  
```

```{r}
ggplot(data = whiptails, aes(x = sex, y = weight)) +
  geom_beeswarm(size = 0.5)
```

```{r}
whiptail_bee <-  ggplot(data = whiptails, aes(x = sex, y = weight)) +
  geom_beeswarm(size = 0.5) +
  geom_boxplot(fill = NA)
```

# Marginal Plot


```{r}
whiptails <- lizards |> 
  filter(common_name == "western whiptail") |> 
  drop_na(total_length, weight) 
```

Plot total length (x-axis) versus weight (y-axis) with point color dependent on sex
```{r}
whiptail_plot <- ggplot(whiptails, aes(x = total_length, y = weight)) +
  geom_point(aes(color = sex)) +
  theme(legend.position = "bottom")

ggMarginal(whiptail_plot, type = "boxplot", groupColour = TRUE) 



```

```{r}
((whiptail_bee + whiptail_plot) /whiptail_bee) & theme_wsj()
```

